### ISSUE TITLE
TasPanel positions.csv rotated 90 degrees?

### ISSUE THREAD

**Issue by bai-yi-bai** [revk/Tasmotizer-PCB#1]
Hi, cool project. Thank you for supporting open hardware.

I planned on getting some faikin32's produced at JLCPCB because I'm a long, long away from the UK and USA.

It seems the positions are not rotated 90 degrees from the PCB. I tried using JLCPCB's autofit, but it didn't work.
![image](https://github.com/revk/Tasmotizer-PCB/assets/72658127/36fbfd97-30a8-4f4f-88ec-37bf3d0dcad0)

**Comment by revk** [comment]
That is odd as I use those files myself with jlcpcb!

Maybe remake for kicad?

**Comment by bai-yi-bai** [comment]
It turns out I was able to use an old ESP8266-01 programmer with a ch341 UART. I had five ESP32-Faikins (2024-03-28) made at JLCPCB and was able to program them with esptool.py using a 10k Ohm resistor from the GPIO0 "0" pin to the USB ground through hole. It was very clever of you to include that in the design! Thank you again for making all this open source. I will not need to have a Tasmotizer made. Who knows, maybe JCLPCB didn't like my browser or they updated their software? Regardless, I will close this issue.
