### ISSUE TITLE
Perpendicular pin hole location in case

### ISSUE THREAD

**Issue by reedy** [revk/Tasmotizer-PCB#3]
I printed off https://github.com/revk/Tasmotizer-PCB/blob/163a86f/PCB/Tas/Tas.stl for a recently purchased Tasmotizer.

It seems the hole for the perpendicular pins is in the wrong half of the case

**Comment by reedy** [comment]
![image](https://github.com/revk/Tasmotizer-PCB/assets/67615/e6445120-1bd0-4f87-a963-2809f6b7fd04)
![image](https://github.com/revk/Tasmotizer-PCB/assets/67615/36937d9b-9b43-42ed-93d7-020e0a72e76b)
![image](https://github.com/revk/Tasmotizer-PCB/assets/67615/cdac3655-8ad8-413f-99b4-4096e9d9f36d)

**Comment by revk** [comment]
Ah, I need to update the 3D model. They used to be that side. Sorry. Will get on to that later.

**Comment by revk** [comment]
This will take longer than expected, something wrong with the code to make the models since latest MacOS. I'll work on it.

**Comment by reedy** [comment]
No rush on my part! :)

It was one of those, trying to put it together and wondering if I was missing something obvious. And was like, no, it's gotta be that way around because of the dimples for the bottom of the horizontal pins...

**Comment by revk** [comment]
OK, the issue is the latest KiCAD. This has totally broken my STL generation tool.

I need to work out what has changed and how. This could take some time.

**Comment by revk** [comment]
OK have a look now, it may be better.
